url: '' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '/profile-site-jekyll' # the subpath of your site, e.g. /blog
title: 'profile site jekyll' # the name of your site, e.g. ACME Corp.
description: Just testing out Jekyll
